import can                                                                                                                                                                                                                                                                    
import time                                                                                                                                                                                                                                                                   
index = 13                                                                                                                                                                                                                                                         
data = []                                                                                                                                                                                                                                                                     
padding = [0x00 for x in range(0x40)]                                                                                                                                                                                                                                         
bus = can.interface.Bus(interface='socketcan',channel='vcan0',bitrate=500000)                                                                                                                                                                                                 
more_message = can.Message(arbitration_id=0x7E0, dlc=0x3,data=[0x30,0x00,0x00],is_extended_id=False)            
for addr in range(0x4C0000,0x610000,0x10000):             
                                                                                                                                                     
    for hex_value in range(addr,addr+0x10000,0x40):                                                                                                                                                                                                                               
        byte1 = hex_value >> 0x18 & 0xff                                                                                                                                                                                                                                          
        byte2 = hex_value >> 0x10 & 0xff                                                                                                                                                                                                                                          
        byte3 = hex_value >> 0x8 & 0xff                                                                                                                                                                                                                                           
        byte4 = hex_value & 0xff                                                                                                                                                                                                                                                  
        msg1 = can.Message(arbitration_id=0x7E0, dlc=0x8,data=[0x07,0x23,0x14,byte1,byte2,byte3,byte4,0x40],is_extended_id=False)                                                                                                                                                 
        bus.send(msg1)                                                                                                                                                                                                                                                            
        time.sleep(0.01)                                                                                                                                                                                                                                                          
        recv_msg = list(bus.recv().data)                                                                                                                                                                                                                                          
        if recv_msg[1] == 0x7F:                                                                                                                                                                                                                                                   
            print(f"skipping address at {hex(hex_value)}")                                                                                                                                                                                                                        
            recv_msg += padding                                                                                                                                                                                                                                                   
            continue                                                                                                                                                                                                                                                              
        data += recv_msg[2:7]                                                                                                                                                                                                                                                     
        size = 0x3A                                                                                                                                                                                                                                                               
        bus.send(more_message)                                                                                                                                                                                                                                                    
        while(size > 0):                                                                                                                                                                                                                                                          
            recv_msg = list(bus.recv().data[1:7])                                                                                                                                                                                                                                 
            size -= 0x7                                                                                                                                                                                                                                                           
            data += recv_msg[1:7]                                                                                                                                                                                                                                                 
        # receiving first frame except data size byte                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                    
    with open(f"dump{index}.bin","wb") as f:                                                                                                                                                                                                                                              
        f.write(bytes(data))                                                                                                                                                                                                                                                      
        index +=1

